services:

    shapecode_cron.cronjob_manager:
        class: Shapecode\Bundle\CronBundle\Manager\CronJobManager
        arguments:
            - '@kernel'
            - '@annotation_reader'
            - '@doctrine.orm.default_entity_listener_resolver'

    shapecode_cron.command.generic_clean_up_daily:
        class: Shapecode\Bundle\CronBundle\CronJob\GenericCleanUpDailyCommand
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: console.command }
            - { name: shapecode_cron.cron_job, expression: '@daily' }

    shapecode_cron.command.generic_clean_up_hourly:
        class: Shapecode\Bundle\CronBundle\CronJob\GenericCleanUpHourlyCommand
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: console.command }
            - { name: shapecode_cron.cron_job, expression: '@hourly' }
