services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $autoPrune: '%shapecode_cron.results.auto_prune%'
            $pruneInterval: '%shapecode_cron.results.interval%'

    # manager
    Shapecode\Bundle\CronBundle\Manager\CronJobManager: ~
    Shapecode\Bundle\CronBundle\Manager\CronJobManagerInterface: '@Shapecode\Bundle\CronBundle\Manager\CronJobManager'

    # commands
    Shapecode\Bundle\CronBundle\Command\CronJobEditCommand: ~
    Shapecode\Bundle\CronBundle\Command\CronProcessCommand: ~
    Shapecode\Bundle\CronBundle\Command\CronPruneLogsCommand: ~
    Shapecode\Bundle\CronBundle\Command\CronRunCommand: ~
    Shapecode\Bundle\CronBundle\Command\CronScanCommand: ~
    Shapecode\Bundle\CronBundle\Command\CronStatusCommand: ~

    # cronjobs
    Shapecode\Bundle\CronBundle\CronJob\GenericCleanUpDailyCommand:
        tags:
            - { name: console.command }
            - { name: shapecode_cron.cron_job, expression: '@daily' }

    Shapecode\Bundle\CronBundle\CronJob\GenericCleanUpHourlyCommand:
        tags:
            - { name: console.command }
            - { name: shapecode_cron.cron_job, expression: '@hourly' }

    # event listener
    Shapecode\Bundle\CronBundle\EventListener\EntitySubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Shapecode\Bundle\CronBundle\EventListener\AnnotationJobLoaderListener: ~
    Shapecode\Bundle\CronBundle\EventListener\ResultAutoPruneListener: ~
    Shapecode\Bundle\CronBundle\EventListener\ServiceJobLoaderListener: ~

    # service
    Shapecode\Bundle\CronBundle\Service\CronJobResultServiceInterface: '@Shapecode\Bundle\CronBundle\Service\CronJobResultService'
    Shapecode\Bundle\CronBundle\Service\CronJobResultService: ~
