services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shapecode\Bundle\CronBundle\:
        resource: '../../*'
        exclude:
            - '../../{Attribute,Collection,Console,DependencyInjection,Domain,Entity,Event,Model,Resources,ShapecodeCronBundle.php}'
